version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.22
    # restart: always
    environment:
      MYSQL_DATABASE: "agenda"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "admin"
      # You can use whatever password you like
      MYSQL_PASSWORD: "root"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"

    volumes:
      - .my-db:/var/lib/mysql
