# Generated by Django 3.1.7 on 2021-04-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome contato')),
                ('sobrenome', models.CharField(blank=True, max_length=255, verbose_name='sobrenome contato')),
                ('telefone', models.CharField(max_length=13, verbose_name='telefone contato')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='email contato')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='data criacao contato')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao contato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.categoria', verbose_name='categoria contato')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
            },
        ),
    ]
